version: "3.9"

services:
  db:
    image: postgres:15
    container_name: clinic_postgres
    restart: always
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
